export const product = [
    {id:1, title: 'Product 1', image: 'src/assets/camra01.jpg', price: 120},
    {id:2, title: 'Product 2', image: 'src/assets/camra02.jpg', price: 800}, 
    {id:3, title: 'Product 3', image: 'src/assets/camra03.jpg', price: 900},
    {id:4, title: 'Product 4', image: 'src/assets/camra04.jpg', price: 500},
    {id:5, title: 'Product 5', image: 'src/assets/camra05.jpg', price: 550},
    {id:6, title: 'Product 6', image: 'src/assets/camra02g.jpg', price: 300},
    {id:7, title: 'Product 7', image: 'src/assets/camra01g.jpg', price: 700},
    {id:8, title: 'Product 8', image: 'src/assets/camra07.jpg', price: 100},
    {id:9, title: 'Product 9', image: 'src/assets/camra06.jpg', price: 150},
    {id:10, title: 'Product 10', image: 'src/assets/camra03g.jpg', price: 160},
    {id:11, title: 'Product 11', image: 'src/assets/camra01.jpg', price: 150},
    {id:12, title: 'Product 12', image: 'src/assets/card-large-item4.jpg', price: 250},
    {id:13, title: 'Product 13', image: 'src/assets/card-large-item5.jpg', price: 350},
    {id:14, title: 'Product 14', image: 'src/assets/card-large-item6.jpg', price: 250},
    {id:15, title: 'Product 15', image: 'src/assets/card-large-item10.jpg', price: 100},
    {id:16, title: 'Product 16', image: 'src/assets/card-large-item11.jpg', price: 190},
    {id:17, title: 'Product 17', image: 'src/assets/card-large-item12.jpg', price: 180},

]